name: Run Postman Collection with Newman

# on:
#   schedule:
#     - cron: '0 */2 * * *'  # Runs every two hours
#   workflow_dispatch:  # Allows manual triggering of the workflow

on:
  push:
    branches:
    - main  # Specify the branch you want to monitor for pushes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: |
          npm install
          npm install -g newman

      - name: Run Postman Collection
        run: newman run postman-collection.json --reporters cli,json --reporter-json-export newman-report.json
        continue-on-error: true
        
    
      - name: List files after running Postman Collection
        run: ls -la

      - name: Set up SSH Tunnel
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          ssh -o StrictHostKeyChecking=no -f -N -L 3306:db-mumbai.raxa.io:3306 centos@backend2.raxa.io

      - name: Save Results to MySQL
        run: |
          npm install
          npm run save-results
        env:
          DB_HOST: '127.0.0.1'
          DB_PORT: 3306
          DB_USER: Staging_Service
          DB_PASSWORD: synecD0che
          DB_NAME: api_testing
